services:
  postgres:
    image: postgres:17-alpine
    container_name: tessera-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: tessera
      POSTGRES_PASSWORD: tessera
      POSTGRES_DB: tessera
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ['CMD-SHELL', 'pg_isready -U tessera -d tessera']
      interval: 5s
      timeout: 3s
      retries: 10

  redis:
    image: redis:7-alpine
    container_name: tessera-redis
    restart: unless-stopped
    ports:
      - '6379:6379'
    command: ['redis-server', '--appendonly', 'yes']
    volumes:
      - redis_data:/data
    healthcheck:
      test: ['CMD', 'redis-cli', 'ping']
      interval: 5s
      timeout: 3s
      retries: 10

  mailhog:
    image: mailhog/mailhog:latest
    container_name: tessera-mailhog
    restart: unless-stopped
    ports:
      - '1025:1025'
      - '8025:8025'

  minio:
    # quay.io: MinIO retiro sus imagenes de Docker Hub.
    image: quay.io/minio/minio:latest
    container_name: tessera-minio
    restart: unless-stopped
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
    ports:
      - '9000:9000'
      - '9001:9001'
    command: server /data --console-address ':9001'
    volumes:
      - minio_data:/data

volumes:
  postgres_data:
  redis_data:
  minio_data:
